name: Echo Message
description: Print a message to the console

inputs:
  message:
    description: The message to print
    required: true

runs:
  using: "composite"
  steps:
    - name: Print message
      shell: bash
      run: |
        echo "Message: ${{ inputs.message }}"
