name: Maven Build
description: Print a message to the console

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Download JaCoCo Agent
      shell: bash
      run: |
        wget https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.13/org.jacoco.agent-0.8.13-runtime.jar -O jacocoagent.jar
        wget https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.13/org.jacoco.cli-0.8.13-nodeps.jar -O jacococli.jar

    - name: Run Tests with JaCoCo Agent
      shell: bash
      run: mvn clean test -DargLine="-javaagent:jacocoagent.jar=destfile=target/jacoco.exec,append=false"

    - name: Compile and Package Project
      shell: bash
      run: mvn package #-X #-X 啟用Maven詳細log

    - name: Generate JaCoCo Report
      shell: bash
      run: |
        java -jar jacococli.jar report \
          target/jacoco.exec \
          --classfiles target/classes/org/example/HelloWorld.class \
          --sourcefiles src/main/java/org/example/HelloWorld.java \
          --html target/site/jacoco

    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/
        retention-days: 1