name: Debug Environment Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允許手動觸發以便快速測試

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: AWS  # 保留 environment: AWS 測試環境級別變量
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image
      DEPLOY_TO_LAMBDA: ${{ vars.DEPLOY_TO_LAMBDA || 'false' }}
      DOCKER_BUILD: ${{ vars.DOCKER_BUILD || 'false' }}
    steps:
      - name: Debug environment variables
        run: |
          echo "Repository-level AWS_ACCOUNT_ID is set: ${{ secrets.AWS_ACCOUNT_ID != '' }}"
          echo "Environment-level AWS_ACCOUNT_ID is set: ${{ env.AWS_ACCOUNT_ID != '' }}"
          echo "ECR_REPO: ${{ env.ECR_REPO }}"
          echo "DEPLOY_TO_LAMBDA: ${{ env.DEPLOY_TO_LAMBDA }}"
          echo "DOCKER_BUILD: ${{ env.DOCKER_BUILD }}"
          echo "GitHub Environment: ${{ github.event.repository.environment || 'Not set' }}"