name: Main Workflow

on:
  push:
    branches:
      - yml-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: yml-test

      - name: Debug
        run: |
          echo "Running on yml-test branch"
          ls -la .github/workflows/

      - name: Call Echo Action
        uses: ./.github/workflows/echo-action.yml
        with:
          message: "Hello from Main Workflow"