name: Test Composite Action

on:
  push:
    branches: [yml-test-disable]

jobs:
  test-composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call local composite action
        uses: ./.github/actions/echo-message
        with:
          message: "Hello from composite action"