name: Main Workflow

on:
  push:
    branches:
      - yml-test

jobs:
  prebuild-java:
    environment: AWS
    runs-on: ubuntu-latest
    outputs:
      build-type: ${{ steps.export.outputs.build-type }}
      aws-region: ${{ steps.export.outputs.aws-region }}
      aws-bucket: ${{ steps.export.outputs.aws-bucket }}
      deployToLambda: ${{ steps.export.outputs.deployToLambda }}

    steps:
      - id: export
        run: |
          echo "build-type=${{ vars.BUILD_TYPE }}" >> $GITHUB_OUTPUT
          echo "aws-region=${{ vars.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "aws-bucket=${{ vars.AWS_S3_BUCKET_JAR }}" >> $GITHUB_OUTPUT
          echo "deployToLambda=${{ vars.DEPLOY_TO_LAMBDA }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

  call-docker:
    needs: prebuild-java
    if: ${{ needs.prebuild-java.outputs.build-type == 'docker' }}
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-docker.yml@yml-test
    with:
      aws-region: ${{ needs.prebuild-java.outputs.aws-region }}
      deployToLambda: ${{ needs.prebuild-java.outputs.deployToLambda }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image

  call-s3:
    needs: prebuild-java
    if: ${{ needs.prebuild-java.outputs.build-type == 's3' }}
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-docker.yml@yml-test
    with:
      aws-region: ${{ needs.prebuild-java.outputs.aws-region }}
      aws-bucket: ${{ needs.prebuild-java.outputs.aws-bucket }}
      deployToLambda: ${{ needs.prebuild-java.outputs.deployToLambda }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}