name: Main Workflow

on:
  push:
    branches:
      - yml-test
env:
  BUILD_TYPE: ${{ vars.BUILD_TYPE || 'docker' }}

jobs:
  prebuild-java:
    environment: AWS
    runs-on: ubuntu-latest
    outputs:
      build-type: ${{ steps.export.outputs.build-type }}

    steps:
      - id: export
        run: echo "build-type=${{ vars.BUILD_TYPE }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show build type
        run: echo "BUILD_TYPE = ${{ vars.BUILD_TYPE }}"

  call-docker:
    needs: prebuild-java
    if: ${{ needs.set-env.outputs.build-type == 'docker' }}
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-docker.yml@yml-test
    with:
      aws-region: ${{ vars.AWS_REGION }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image

  call-s3:
    needs: prebuild-java
    if: ${{ needs.set-env.outputs.build-type == 's3' }}
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-s3.yml@yml-test
    with:
      aws-region: ${{ vars.AWS_REGION }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image