name: Main Workflow

on:
  push:
    branches:
      - yml-test
      -
jobs:
  prebuild-java:
    environment: AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Docker Info
        run: |
          echo "hello"

  call-docker:
    needs: prebuild-java
    if: ${{ vars.BUILD_TYPE }} == 'docker'
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-docker.yml@yml-test
    with:
      aws-region: ${{ vars.AWS_REGION }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image

  call-s3:
    needs: prebuild-java
    if: ${{ vars.BUILD_TYPE }} == 's3'
    uses: Roshiahsu/my-lambda-app/.github/workflows/build-docker.yml@yml-test
    with:
      aws-region: ${{ vars.AWS_REGION }}
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-3.amazonaws.com/my-lambda-image